{% set name = "napari-tools-menu" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-tools-menu-{{ version }}.tar.gz
  sha256: 0cb4c21ed55452bda7601c0636d678409f35af17a98a2f427201051faa00c051

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7

test:
  imports:
    - napari_tools_menu
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-tools-menu
  summary: Attaches a customizable Tools menu to napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
